on:
  push:
  schedule:
    - cron: '0 0 */1 * *'

name: docker-registry-cn-mirror-test

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      TX_CD_IP: ${{secrets.TX_CD_IP}}
      TX_CD_PASS: ${{secrets.TX_CD_PASS}}
    steps:
      - name: install
        run: |
          sudo apt update
          sudo apt install -y sshpass

      - name: docker version
        run: sshpass -p $TX_CD_PASS ssh -p 22 -o StrictHostKeyChecking=no root@$TX_CD_IP "docker version"

      - name: docker info
        run: sshpass -p $TX_CD_PASS ssh -p 22 -o StrictHostKeyChecking=no root@$TX_CD_IP "docker info"

      - name: Test
        run: |
          tee ./mirror.sh <<-'EOF'
          registrys="
          docker.io
          dockerhub.azk8s.cn
          mirror.ccs.tencentyun.com
          $ALIYUN_MIRROR
          $HUAWEI_MIRROR
          "
          image="library/nginx:1.17.6-alpine"

          for registry in $registrys
          do
             time docker pull $registry/$image \
               && echo -e "\033[32m$registry is good\033[0m" \
               || echo -e "\033[31m$registry is outdated\033[0m"
             docker rmi $registry/$image || true
          done
          EOF
          sshpass -p $TX_CD_PASS ssh -p 22 -o StrictHostKeyChecking=no root@$TX_CD_IP "export ALIYUN_MIRROR="$ALIYUN_MIRROR"; export HUAWEI_MIRROR="$HUAWEI_MIRROR"; bash -s" < mirror.sh
        env:
          ALIYUN_MIRROR: ${{secrets.ALIYUN_MIRROR}}
          HUAWEI_MIRROR: ${{secrets.HUAWEI_MIRROR}}